---
- name: configure and launch go app server
  hosts: app
  remote_user: root
  become: true

  tasks:
    - name: install golang
      yum:
        name: golang
        state: latest

    - name: create directory for golang
      file:
        path: /root/go
        state: directory

    - name: copy go app file to servers
      copy:
        src: /home/ansadmin/app.go
        dest: /root/go

    - name: run go app
      command: go run /root/go/app.go